# Nginx Dynamic Hosts
server {
    listen 80 default_server;
    listen [::]:80 default_server;

    # catch all non-www domains
    server_name localhost;

    root /var/www;

    location / {
        try_files $uri $uri/ /index.php?$args;

        index index.php index.html index.htm;
    }

    location ~* \.php$ {
        fastcgi_pass   php:9000;
        include        fastcgi_params;
        fastcgi_param  SCRIPT_FILENAME $document_root$fastcgi_script_name;
        fastcgi_param  SCRIPT_NAME     $fastcgi_script_name;
    }
}

# Redirect HTTP to HTTPS (except localhost)
server {
    listen 80;
    server_name ~(?<domain>.+)\.local$;

    # Redirect HTTP to HTTPS
    return 301 https://$host$request_uri;
}

# Nginx Dynamic Hosts
server {
    listen 443 ssl;

    # catch all non-www domains
    server_name ~(?<domain>.+)\.local$;

    root /var/www/$domain/public;
    index index.php index.html index.htm;

    # SSL configuration
    ssl_certificate /etc/nginx/certs/localhost.crt;
    ssl_certificate_key /etc/nginx/certs/localhost.key;
    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_ciphers HIGH:!aNULL:!MD5;

    # logs por ano-mes (YYYY-MM)
    if ($time_iso8601 ~ "^(\d+)-(\d+)") {
        set $ym "$1-$2";
    }

    access_log /var/log/nginx/access.log;
    error_log  /var/log/nginx/error.log;

    location / {

        try_files $uri $uri/ /index.php?$args;

        index index.php index.html index.htm;
    }

    location ~ \.php$ {
        fastcgi_pass php:9000;
        fastcgi_index index.php;
        fastcgi_intercept_errors on;
        fastcgi_param SCRIPT_FILENAME  $document_root$fastcgi_script_name;
        include fastcgi_params;
        fastcgi_buffers 16 16k;
        fastcgi_buffer_size 32k;
    }

    location ~* \.(eot|ttf|woff|woff2)$ {
        add_header Access-Control-Allow-Origin *;
    }
}
